### ISSUE TITLE
mousedown影响一些网页的正常功能

### ISSUE THREAD

**Issue by Cat7373** [Cat7373/remove-web-limits#1]
比如Google翻译的语言切换

**Comment by Cat7373** [comment]
暂时没找到什么好办法，在有影响的时候暂时禁用脚本搞定吧- -
也希望有高手能提供点好的解决方案- -
至于黑名单的办法，不希望引入这种机制。。。

**Comment by xgqfrms** [comment]
IE系列：为什么没有呀？

**Comment by Cat7373** [comment]
@xgqfrms 没找到IE安装用户脚本的方式。
