### ISSUE TITLE
影响youtube播放

### ISSUE THREAD

**Issue by adasqg** [Cat7373/remove-web-limits#11]
多次调进度，声音，暂停开始，全屏关全屏，就会使youtube这个网页假死不动。

**Comment by Cat7373** [comment]
噗，我也发现这个问题了，一开始还以为是代理或者油管的问题呢- -
原来是这个脚本的问题- -
有空出个官方自带的屏蔽网站列表吧。。。

**Comment by Cat7373** [comment]
已经增加到自带的排除规则中，稍后发布新稳定版。
